name: Set Branch Protection Rules for dev

on:
  push:
    branches:
      - dev # or any default branch where you want this action to trigger

jobs:
  protect-dev-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Protection Rules
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/dev/protection \
            -d '{
              "required_status_checks": null,
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismissal_restrictions": {},
                "dismiss_stale_reviews": false,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 1
              },
              "restrictions": null
            }'
